In [25]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [9]:
import pandas as pd
df=pd.read_csv('/content/drive/My Drive/ML dataset/Dataset of Diabetes.csv')
df.head()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N

In [11]:
df.describe()

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI
count,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,340.500000,2.705514e+05,53.528000,5.124743,68.943000,8.281160,4.862820,2.349610,1.204750,2.609790,1.854700,29.578020
std,240.397673,3.380758e+06,8.799241,2.935165,59.984747,2.534003,1.301738,1.401176,0.660414,1.115102,3.663599,4.962388
min,1.000000,1.230000e+02,20.000000,0.500000,6.000000,0.900000,0.000000,0.300000,0.200000,0.300000,0.100000,19.000000
25%,125.750000,2.406375e+04,51.000000,3.700000,48.000000,6.500000,4.000000,1.500000,0.900000,1.800000,0.700000,26.000000
50%,300.500000,3.439550e+04,55.000000,4.600000,60.000000,8.000000,4.800000,2.000000,1.100000,2.500000,0.900000,30.000000
75%,550.250000,4.538425e+04,59.000000,5.700000,73.000000,10.200000,5.600000,2.900000,1.300000,3.300000,1.500000,33.000000
max,800.000000,7.543566e+07,79.000000,38.900000,800.000000,16.000000,10.300000,13.800000,9.900000,9.900000,35.000000,47.750000

In [10]:
pd.isnull(df).sum()

ID           0
No_Pation    0
Gender       0
AGE          0
Urea         0
Cr           0
HbA1c        0
Chol         0
TG           0
HDL          0
LDL          0
VLDL         0
BMI          0
CLASS        0
dtype: int64

In [21]:
df.isnull().sum()[df.isnull().sum()>0]

Series([], dtype: int64)

In [20]:
import numpy as np
print(df['Urea'].unique())
print(df['Urea'].nunique())

[ 4.7    4.5    7.1    2.3    2.     2.6    3.6    4.4    3.3    3.
  4.6    3.5    5.5    5.9    2.2    3.8   13.5    5.     5.3    4.
  3.2    4.8    4.2    4.3    7.5    5.6    6.     3.4    4.1    2.7
  5.7    3.7    3.1    2.4    5.4    2.1    3.9    2.8    7.6    6.8
  5.2    6.3    6.6    5.8   10.     9.6    7.3   22.     6.1   17.1
  7.7    1.8    5.1    9.1    8.5    6.5    4.16   8.7   20.8    1.2
  2.9   14.1    9.9    9.3   11.7    7.8    4.9    8.    20.     4.66
 14.     6.2    5.66   6.66   3.66  10.5    7.     6.4   10.4    1.9
  3.33   8.6    2.5   14.5    8.9    6.7   11.3   11.     0.5   13.2
 24.    10.3    7.4    6.833 11.1   13.3    7.9    7.2    1.1    9.
 14.9    4.33   9.2   11.2   38.9    6.9   26.4    8.1    8.2    8.8  ]
110

In [23]:
from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()
df['CLASS'] = le.fit_transform(df['CLASS'])
df['Gender'] = le.fit_transform(df['Gender'])

print("Encoded 'Gender' unique values:", df['Gender'].unique())
print("Encoded 'CLASS' unique values:", df['CLASS'].unique())
display(df.head())

Encoded 'Gender' unique values: [0 1 2]
Encoded 'CLASS' unique values: [0 1 2 3 4]

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,0,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,0
1,735,34221,1,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,0
2,420,47975,0,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,0
3,680,87656,0,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,0
4,504,34223,1,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,0

In [26]:
import pandas as pd
df=pd.read_csv('/content/drive/My Drive/ML dataset/adult.csv')
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [35]:
df.replace('?', np.nan,inplace=True)
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,4,226802,11th,7,4,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,4,89814,HS-grad,9,2,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,2,336951,Assoc-acdm,12,2,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,4,160323,Some-college,10,2,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,0,103497,Some-college,10,4,NaN,Own-child,White,Female,0,0,30,United-States,<=50K

In [27]:
df.describe()

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [36]:
df.isnull().sum()[df.isnull().sum()>0]

occupation        2809
native-country     857
dtype: int64

In [29]:
import numpy as np
print(df['occupation'].unique())
print(df['occupation'].nunique())

['Machine-op-inspct' 'Farming-fishing' 'Protective-serv' '?'
 'Other-service' 'Prof-specialty' 'Craft-repair' 'Adm-clerical'
 'Exec-managerial' 'Tech-support' 'Sales' 'Priv-house-serv'
 'Transport-moving' 'Handlers-cleaners' 'Armed-Forces']
15

In [32]:
from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()
df['workclass'] = le.fit_transform(df['workclass'])
df['marital-status'] = le.fit_transform(df['marital-status'])

print("Encoded 'workclass' unique values:", df['workclass'].unique())
print("Encoded 'marital-status' unique values:", df['marital-status'].unique())

Encoded 'workclass' unique values: [4 2 0 6 1 7 5 8 3]
Encoded 'marital-status' unique values: [4 2 6 0 5 3 1]

Once your Drive is mounted, you should see a folder structure under `/content/drive/My Drive/`. Please update the code in the next cell to reflect the correct path to your `diabetes data.csv` file in your Google Drive. For example, if your file is directly in 'My Drive', the path would be `/content/drive/My Drive/diabetes data.csv`.